Template app created
yuyuyuno/Garmon-i-ya pull request #1
Opened 2022-10-11 22:12 UTC by yuyuyuno

2022-10-11 23:46 UTC, khafizovas requested changes

2022-10-11 23:46 UTC, khafizovas commented on api/app.js
> +var app = express();
`var` лучше заменить на `const` и стараться не использовать `var` в принципе никогда в жизни.

2022-10-11 23:46 UTC, khafizovas commented on api/app.js
> +app.set('views', path.join(__dirname, 'views'));
Можно вынести конфигурацию подключаемых к `app` фич в отдельные вспомогательные методы, принимающие параметром `app`. В папку `helpers` положить, например.

2022-10-11 23:46 UTC, khafizovas commented on api/app.js
> +app.use(function(req, res, next) {
Можно вынести параметр `app.use` в функцию в `helpers`, чтобы было говорящее название, и импортировать, куда нужно. Будет более читаемо с точки зрения декомпозиции. Подключать так же как и подключаемые либами фичи, то есть в каком-то методе для конфигурации.

2022-10-11 23:46 UTC, khafizovas commented on api/app.js
> +app.use('/', indexRouter);
Лучше переместить в `routes` все маршруты.

2022-10-11 23:46 UTC, khafizovas commented on api/bin/www
> +#!/usr/bin/env node
Можно не хранить в отдельной директории этот файл, а сделать структуру наподобие следующей:
- app.js
- routes/
- controllers/
- logic/
- db/

2022-10-11 23:46 UTC, khafizovas commented on api/bin/www
> +/**
Этот комментарий избыточен, импорты есть импорты.

2022-10-11 23:46 UTC, khafizovas commented on api/bin/www
> + * Get port from environment and store in Express.
Такие комментарии говорят о необходимости вынести код, к которому они относятся, в отдельные функции, то есть это как бы подзадача, которую нежелательно решать в едином пласте с другими – да и вообще на каждую по функции – структурная декомпозиция.

2022-10-11 23:46 UTC, khafizovas commented on api/bin/www
> +    ? 'Pipe ' + port
Желательно использовать не конкатенацию, а интерполяцию.

2022-10-11 23:46 UTC, khafizovas commented on client/README.md
> +# Getting Started with Create React App
Можно написать в этом файле что-то о структуре клиентской части приложения, например, или какие-то более общие вещи, но не настолько общие как шаблонный текст.

2022-10-11 23:46 UTC, khafizovas commented on client/public/index.html
> +    <!--
Можно удалить комментарии.

2022-10-11 23:46 UTC, khafizovas commented on client/public/index.html
> +  <head>
Где-то в этом блоке можно прописать заголовок страницы.

2022-10-11 23:46 UTC, khafizovas commented on client/public/index.html
> +    <link rel="icon" href="%PUBLIC_URL%/favicon.ico" />
От иконок по умолчанию и прочей такой мишуры тоже можно смело избавляться, удалив и использование их в коде, и сами файлы.

2022-10-11 23:46 UTC, khafizovas commented on client/public/manifest.json
> +  "icons": [
Убрать, если иконки будут удалены.

2022-10-11 23:46 UTC, khafizovas commented on client/src/App.css
> +.App {
Файл можно удалить за ненадобностью. Глобальные стили в `index.css`, остальные в директориях соответствующих компонентов.

2022-10-11 23:46 UTC, khafizovas commented on client/src/App.js
> +  const callAPI = () => {
Для совершения запросов лучше использовать библиотеку `axios`, а такие методы выносить в кастомные хуки.

2022-10-11 23:46 UTC, khafizovas commented on client/src/index.js
> +// If you want to start measuring performance in your app, pass a function
Можно убрать комментарий.

2022-10-16 00:15 UTC, yuyuyuno commented on api/app.js
> +app.set('views', path.join(__dirname, 'views'));
Убрала views, не нужны!

2022-10-16 00:15 UTC, yuyuyuno commented on api/app.js
> +app.use('/', indexRouter);
Маршруты тоже удалены.

2022-10-16 00:56 UTC, khafizovas approved these changes

2022-10-16 00:57 UTC, merged